=== Linlang-Wyl/Ulin_html/3.21/book.dtd
<?xml version="1.1" encoding="UTF-8”?>
<!ELEMENT library (articles+)>
<!ELEMENT articles (dc:title, dc:creator, dc:publisher, dc:date, dc:description?, dc:format?, dc:language?, dc:identifier?, dc:subject?, dc:type?, dc:rights?)>

<!ELEMENT dc:title (#PCDATA)>
<!ELEMENT dc:creator (#PCDATA)>
<!ELEMENT dc:publisher (#PCDATA)>
<!ELEMENT dc:date (#PCDATA)>
<!ELEMENT dc:description (#PCDATA)>
<!ELEMENT dc:format (#PCDATA)>
<!ELEMENT dc:language (#PCDATA)>
<!ELEMENT dc:identifier (#PCDATA)>
<!ELEMENT dc:subject (#PCDATA)>
<!ELEMENT dc:type (#PCDATA)>
<!ELEMENT dc:rights (#PCDATA)>
<!ELEMENT dc:rights (#PCDATA)>
<!ATTLIST articles id ID #IMPLIED>

=== Linlang-Wyl/Ulin_html/3.21/work.xml
<!DOCTYPE library SYSTEM "book.dtd">
<library xmlns:dc="http://purl.org/dc/elements/1.1/">
  <articles>
    <dc:title>Internet实用技术</dc:title>
    <dc:creator>邓三鸿 等</dc:author>
    <dc:publisher>清华大学出版社</dc:publisher>
    <date>2010</date>
    <dc:description>本书介绍了互联网的基础知识、网络编程、网络应用等方面的内容。</dc:description>
    <dc:format>图书</dc:format>
    <dc:language>中文</dc:language>
    <dc:identifier>ISBN 978-7-302-22581-4</dc:identifier>
    <dc:subject>互联网技术</dc:subject>
    <dc:type>Text</dc:type>
    <dc:rights>版权所有</dc:rights>
  </articles>
</library>
